---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  - name: instances-volumes-ec2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      all:
        ansible_user: stackmate
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: aws-efs
  converge_sequence:
    - converge
  destroy_sequence:
    - cleanup
  test_sequence:
    - lint
    - syntax
    - converge
    - verify
