---
- name: Converge
  hosts: all
  gather_facts: no

  roles:
    - role: routing

  pre_tasks:
    - name: Creating an EC2 Keypair to be used with the instance
      delegate_to: localhost
      ec2_key:
        state: present
        name: "{{ keypair_name }}"
        key_material: "{{ public_key }}"
        aws_access_key: "{{ providers.aws.access_key }}"
        aws_secret_key: "{{ providers.aws.secret }}"
        security_token: "{{ providers.aws.token }}"
        region: "{{ region }}"
      register: keypair

    - name: Deploying an EC2 instance to be used for routing
      delegate_to: localhost
      ec2_instance:
        state: present
        name: routing-tests-instance
        key_name: "{{ keypair_name }}"
        vpc_subnet_id: "{{ main_vpc_subnet_id }}"
        instance_type: t2.nano
        termination_protection: no
        security_groups:
          - default
        network:
          assign_public_ip: true
        image_id: ami-05c26ae4789875080 # ubuntu 20.04
        region: "{{ region }}"
        aws_access_key: "{{ providers.aws.access_key }}"
        aws_secret_key: "{{ providers.aws.secret }}"
        security_token: "{{ providers.aws.token }}"
        wait: yes
        tags:
          Name: routing-tests-instance
          Environment: "{{ stage }}"
          Group: application
      register: testinstance

  post_tasks:
    - name: Terminating created resources
      include_tasks: ../../tasks/aws/terminations.yml
      loop: "{{ provisions }}"

    - name: Destroying the EC2 instance
      delegate_to: localhost
      ec2_instance:
        state: absent
        name: routing-tests-instance
        region: "{{ region }}"
        vpc_subnet_id: "{{ main_vpc_subnet_id }}"
        aws_access_key: "{{ providers.aws.access_key }}"
        aws_secret_key: "{{ providers.aws.secret }}"
        security_token: "{{ providers.aws.token }}"
        wait: no

    - name: Destroying the EC2 keypair
      delegate_to: localhost
      ec2_key:
        state: absent
        name: "{{ keypair_name }}"
        key_material: "{{ public_key }}"
        aws_access_key: "{{ providers.aws.access_key }}"
        aws_secret_key: "{{ providers.aws.secret }}"
        security_token: "{{ providers.aws.token }}"
        region: "{{ region }}"

    - name: Storing output to a json file
      delegate_to: localhost
      copy:
        content: "{{ vars | to_nice_json }}"
        dest: "{{ playbook_dir }}/provisioning-output.json"
      become: false
      no_log: yes

  vars:
    keypair_name: molecule-test
    vpc_id: vpc-09ebb623125812dd5
    main_vpc_subnet_id: subnet-02eacc03ad59e4568
    alternative_vpc_subnet_id: subnet-0e6064c08d80b3014
    stage: molecule-test
    provider: aws
    flavor: instances
    region: eu-central-1
    hosted_zone_id: Z07543562ESYKGPNP3TXF
    public_key: "{{ lookup('file', '../../../../../../tests/ssh-keys/stackmate-sample-key.pub') }}"
    ignore_target_registration_errors: yes
    provisions:
      - id: service-routing-abc123
        provision_params:
          kind: routing
          provider: aws
          target_port: 80
          target_group: application
          domain: permanent-molecule-test.myappis.live
          target_instances:
            - "{{ testinstance.instances.0.instance_id }}"
