---
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  - name: localhost
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: aws-vpc-preview-domain
  converge_sequence:
    - converge
  destroy_sequence:
    - cleanup
  test_sequence:
    - lint
    - syntax
    - converge
