---
version: 14.x
flavor: instances
apt_cache_timeout: 7200
deployment_user: stackmate
store_state: yes

# Set to true to suppress the UID/GID switching when running package scripts. If
# set explicitly to false, then installing as a non-root user will fail.
npm_config_unsafe_perm: "false"

# packages that are globally available via NPM
npm_global_packages:
  - yarn

# customizable variables
npm_lib_path: "/usr/local/lib/npm"

node_apt_packages:
  - node-mysql

apt_lock_retries: 30
apt_lock_delay: 10
