---
essential_packages:
  - git
  - ntp
  - openssl
  - libssl-dev
  - docker-compose
  - docker.io
  - openssh-server
  - openssh-client
  - resolvconf
  - htop
  - vim
  - build-essential
  - curl
  - libcurl4-openssl-dev
  - wget
  - sudo
  - libffi-dev
  - gpg
  - apt-transport-https
  - gnupg2
  - tzdata
  - rsync
  - software-properties-common
  - python3
  - python3-pip
  - python3-dev
  - python3-setuptools

# ntp configuration
ntp_daemon: ntp
ntp_tzdata_package: tzdata
ntp_driftfile: /var/lib/ntp/drift

# ssh configuration
sshd_service: ssh
sshd_config: /etc/ssh/sshd_config
