FROM stackmate/stackmate-base:0.1

USER root

RUN apt-get update && \
    apt-get install cron \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /workspace
USER stackmate
