---
flavor: instances
deployment_user: stackmate
timezone: Etc/UTC
stackmate_security_group: stackmate-incoming
databases_security_group: database-incoming
store_state: yes
apt_cache_timeout: 7200
apt_lock_retries: 30
apt_lock_delay: 10
provider:
stage:
vpc_id:
vpc_subnet_id:
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_STS_TOKEN') }}"

# rds related variables
rds_subnet_group_name: stackmate-db-subnet
storage_type: gp2

# RDS limitation: we cannot assign the SUPER privilege, hence we cannot grant ALL
# which means we need to list privileges explicitly
mysql_user_grants:
  - SELECT
  - INSERT
  - UPDATE
  - DELETE
  - CREATE
  - DROP
  - RELOAD
  - PROCESS
  - REFERENCES
  - INDEX
  - ALTER
  - SHOW DATABASES
  - CREATE TEMPORARY TABLES
  - LOCK TABLES
  - EXECUTE
  - REPLICATION SLAVE
  - REPLICATION CLIENT
  - CREATE VIEW
  - SHOW VIEW
  - CREATE ROUTINE
  - ALTER ROUTINE
  - CREATE USER
  - EVENT
  - TRIGGER
