---
- name: Deleting obsolete Cloudfront distribution
  delegate_to: localhost
  cloudfront_distribution:
    state: absent
    caller_reference: "{{ item.provision_params.name }}"
    aws_access_key: "{{ providers.aws.access_key }}"
    aws_secret_key: "{{ providers.aws.secret }}"
    security_token: "{{ providers.aws.token }}"
    wait: yes
  async: 7200
  poll: 0
  register: terminated_distribution

- name: Terminating unwanted DNS records related to the terminated Cloudfront distribution
  delegate_to: localhost
  route53:
    state: absent
    type: A
    hosted_zone_id: "{{ hosted_zone_id }}"
    record: "{{ rec.record }}"
    value: "{{ rec.value }}"
    ttl: "{{ dns_records_ttl }}"
    wait: yes
    alias: yes
    overwrite: yes
    alias_hosted_zone_id: "{{ route53_alias_hosted_zone_id }}"
    aws_access_key: "{{ providers.aws.access_key }}"
    aws_secret_key: "{{ providers.aws.secret }}"
    security_token: "{{ providers.aws.token }}"
  loop: "{{ item | cloudfront_terminatable_dns_records(records=dns_records) }}"
  loop_control:
    loop_var: rec
  when: dns_records is defined
  register: removed_records

- name: Storing termination results
  set_fact:
    termination_results: "{{ termination_results | default([]) + [terminated_distribution] }}"
    terminated_dns_records: "{{ terminated_dns_records | default([]) + removed_records.results }}"
