---
- name: Configuring swap file swappiness and cache pressure
  become: yes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "present"
    reload: True
  with_dict: "{{ swapfile_sysctl }}"

- name: Creating the swap file
  become: yes
  command: |
    {% if swapfile_fallocate %}
    fallocate -l {{ ((swapfile_size) | int * 1024 * 1024) }} {{ swapfile_path }}
    {% else %}
    dd if=/dev/zero of={{ swapfile_path }} bs=1M count={{ swapfile_size }}
    {% endif %}
  args:
    creates: "{{ swapfile_path }}"
  register: swapfile_creation

- name: Setting swap file permissions
  become: yes
  file:
    path: "{{ swapfile_path }}"
    state: "file"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Initializing swap file
  become: yes
  command: mkswap {{ swapfile_path }}
  when: swapfile_creation is changed

- name: Enabling swap file
  become: yes
  command: swapon {{ swapfile_path }}
  when: swapfile_creation is changed
  ignore_errors: yes
  register: swapfile_enabling

- name: Adding swapfile entry in /etc/fstab
  become: yes
  mount:
    src: "{{ swapfile_path }}"
    name: "none"
    fstype: "swap"
    opts: "sw,nofail"
    dump: "0"
    passno: "0"
    state: present
  when: swapfile_enabling is changed
