---
provider:
domain:
stage:
region:
flavor: instances
ses_iam_user: stackmatemailer
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_STS_TOKEN') }}"
store_state: yes

# ses specific params
dns_ttl: 3600
is_docker_guest: false
apt_cache_timeout: 7200
apt_lock_retries: 30
apt_lock_delay: 10
regenerate_credentials: false
