---
provider:
region:
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_STS_TOKEN') }}"
store_state: yes
