---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-essentials-role
    image: stackmate/stackmate-base:0.2
    command: /sbin/init
    privileged: yes
    override_command: no
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    env:
      container: docker
      LC_ALL: C
      DEBIAN_FRONTEND: noninteractive
    groups:
      - application
      - workers
      - provisionables
provisioner:
  log: true
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      all:
        ansible_user: stackmate
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - lint
    - verify
