---
provider:
domain:
stage:
region:
appname:
flavor: instances
deployment_path: /var/www/application
deployment_user: stackmate
preview_domain: myappis.live
public_release_path: "{{ deployment_path }}/current"
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_STS_TOKEN') }}"
store_state: yes

default_uri: /
default_ports:
  gunicorn: 3000
  daphne: 3100
  pm2: 4000
  puma: 5000

supported:
  - gunicorn
  - daphne
  - pm2
  - puma

pip_packages:
  - gunicorn
  - daphne

gem_packages:
  - puma

npm_packages:
  - pm2

configurations:
  default_config: &default_config
    after: syslog.target network.target
    requires: syslog.target network.target
    systemd_user: stackmate
    systemd_group: stackmate
    env_file: /etc/stackmate.env
    kill_mode: process

  gunicorn:
    <<: *default_config
    description: Gunicorn application server
    process_type: simple

  daphne:
    <<: *default_config
    description: Daphne application server
    process_type: simple

  pm2:
    <<: *default_config
    process_type: forking
    description: PM2 application server

  puma:
    <<: *default_config
    process_type: simple
    description: Puma ruby app server

profile_script: ~/.profile
system_profile_script: /etc/profile
