---
flavor: instances
deployment_user: stackmate
timezone: Etc/UTC
provider:
stage:
vpc_id:
vpc_subnet_id:
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_STS_TOKEN') }}"
store_state: yes

elb_security_group_name: loadbalancer-incoming
elb_target_group_prefix: loadbalancer-tg
elb_name_prefix: loadbalancer
elb_long_name: load-balancer-production
loadbalancer_ports: [80, 443]
ignore_target_registration_errors: false
dns_records_ttl: 3600
