---
default_config:
  ANSIBLE_PIPELINING: True
  ANSIBLE_TIMEOUT: 5
  HOST_KEY_CHECKING: False
  ANSIBLE_VERBOSITY: 4
  DEFAULT_GATHERING: smart
  ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  TIMEOUT: 15
  ANSIBLE_SSH_TIMEOUT: 15
