---
version: '3.7'
flavor: instances
deployment_user: stackmate
store_state: yes

# Python
apt_lock_retries: 30
apt_lock_delay: 10
apt_cache_timeout: 7200
python_apt_package: "{{ 'python3-apt' if version.startswith('3') else 'python-apt' }}"
pip_package: "{{ 'python3-pip' if version.startswith('3') else 'pip-python' }}"
pip_executable: "{{ 'pip3' if version.startswith('3') else 'pip' }}"
pip_install_packages:
  - setuptools
  - boto3
  - PyMySQL

python_apt_packages:
  - python3-dev
  - python3-setuptools
  - python3-mysqldb
  - python3-postgresql
  - python-sqlite
  - python3-pymysql
  - pipenv
