---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: nginx

  post_tasks:
    - name: Storing output to a json file
      delegate_to: localhost
      copy:
        content: "{{ vars | to_nice_json }}"
        dest: "{{ playbook_dir }}/provisioning-output.json"
      become: false
      no_log: yes

  vars:
    provisions:
      - id: dependency-application-server-nginx
        group: application
        provision_params:
          version: 1.18
