---
- name: Running the watch loop
  include_tasks: 'loop.yml'
  tags:
    - ignore_empty_output

- name: Setting the facts for the iteration
  set_fact:
    watch_finished: "{{ watch_status.finished | bool }}"
    watch_count: "{{ watch_count | int + 1 }}"
    watch_retries: "{{ (watch_timeout | int / watch_poll | int) | int }}"
  tags:
    - ignore_empty_output

- name: Checking for timeout
  fail:
    msg: "Timeout of {{ watch_timeout }} seconds exceeded ({{ watch_retries }} retries)"
  when: (not watch_finished) and (watch_count | int > watch_retries | int)
  tags:
    - ignore_empty_output

- name: Waiting for output
  wait_for:
    timeout: "{{ watch_poll | int }}"
  when: not watch_finished
  tags:
    - ignore_empty_output

- name: Recursively running a watch iteration
  include_tasks: recursive.yml
  when: not watch_finished
  tags:
    - ignore_empty_output
